import { Service } from '../../services/entities/service.entity';

export const servicesSeed: Omit<Service, 'id' | 'user_services'>[] = [
  {
    name: 'Скидка 10% на любую услугу клиники',
    description: '',
    discount_percent: 10,
    original_price: 0,
    cost_coins: 50000,
    icon: 'discount_10',
    is_active: true,
    cooldown_days: 7,
  } as any,
  {
    name: 'Скидка 20% на любую услугу клиники',
    description: '',
    discount_percent: 20,
    original_price: 0,
    cost_coins: 250000,
    icon: 'discount_20',
    is_active: true,
    cooldown_days: 30,
  } as any,
  {
    name: 'Скидка 30% на любую услугу клиники',
    description: '',
    discount_percent: 30,
    original_price: 0,
    cost_coins: 750000,
    icon: 'discount_30',
    is_active: true,
    cooldown_days: 30,
  } as any,
  {
    name: 'Бесплатная чистка зубов',
    description: '',
    discount_percent: 0,
    original_price: 0,
    cost_coins: 500000,
    icon: 'free_cleaning',
    is_active: true,
    cooldown_days: 60,
  } as any,
  {
    name: 'Бесплатная консультация с врачом + снимки + план лечения',
    description: '',
    discount_percent: 0,
    original_price: 0,
    cost_coins: 50000,
    icon: 'free_consultation',
    is_active: true,
    cooldown_days: 7,
  } as any,
  {
    name: 'Имплант в подарок',
    description: '',
    discount_percent: 0,
    original_price: 0,
    cost_coins: 5000000,
    icon: 'free_implant',
    is_active: true,
    cooldown_days: 180,
  } as any,
  {
    name: 'Коронка из диоксида циркония в подарок',
    description: '',
    discount_percent: 0,
    original_price: 0,
    cost_coins: 5000000,
    icon: 'free_crown',
    is_active: true,
    cooldown_days: 180,
  } as any,
  {
    name: 'Обследование на внутриротовом сканере зубов + снимок',
    description: '',
    discount_percent: 0,
    original_price: 0,
    cost_coins: 50000,
    icon: 'scanner',
    is_active: true,
    cooldown_days: 7,
  } as any,
  {
    name: 'Компьютерная томография',
    description: '',
    discount_percent: 0,
    original_price: 0,
    cost_coins: 900000,
    icon: 'tomography',
    is_active: true,
    cooldown_days: 90,
  } as any,
  {
    name: 'Сертификат на 3000 рублей',
    description: '',
    discount_percent: 0,
    original_price: 0,
    cost_coins: 900000,
    icon: 'certificate_3000',
    is_active: true,
    cooldown_days: 90,
  } as any,
  {
    name: 'Сертификат на 5000 рублей',
    description: '',
    discount_percent: 0,
    original_price: 0,
    cost_coins: 1600000,
    icon: 'certificate_5000',
    is_active: true,
    cooldown_days: 90,
  } as any,
];
