import { Upgrade, UpgradeType } from '../../game/entities/upgrade.entity';

export const upgradesSeed: Omit<Upgrade, 'id' | 'user_upgrades'>[] = [
  {
    name: 'Зонд',
    description: '',
    type: UpgradeType.CLICK_POWER,
    base_cost: 72000,
    cost_multiplier: 1.15,
    base_value: 2,
    icon: 'probe',
    is_active: true,
  } as any,
  {
    name: 'Зеркало',
    description: '',
    type: UpgradeType.CLICK_POWER,
    base_cost: 144000,
    cost_multiplier: 1.15,
    base_value: 3,
    icon: 'mirror',
    is_active: true,
  } as any,
  {
    name: 'Гладилка',
    description: '',
    type: UpgradeType.CLICK_POWER,
    base_cost: 288000,
    cost_multiplier: 1.15,
    base_value: 4,
    icon: 'smoother',
    is_active: true,
  } as any,
  {
    name: 'Шприц',
    description: '',
    type: UpgradeType.CLICK_POWER,
    base_cost: 432000,
    cost_multiplier: 1.15,
    base_value: 5,
    icon: 'syringe',
    is_active: true,
  } as any,
  {
    name: 'Набор',
    description: '',
    type: UpgradeType.CLICK_POWER,
    base_cost: 864000,
    cost_multiplier: 1.15,
    base_value: 10,
    icon: 'kit',
    is_active: true,
  } as any,
  {
    name: 'Лоток',
    description: '',
    type: UpgradeType.CLICK_POWER,
    base_cost: 1584000,
    cost_multiplier: 1.15,
    base_value: 20,
    icon: 'tray',
    is_active: true,
  } as any,
  {
    name: 'Ассистент',
    description: '',
    type: UpgradeType.PASSIVE_INCOME,
    base_cost: 2160000,
    cost_multiplier: 1.15,
    base_value: 25,
    icon: 'assistant',
    is_active: true,
  } as any,
];
